### PR TITLE
fix empty conf. key list

### PR DESCRIPTION
**Pull request by JavaIsJavaScript**
Pressing "Perform" without selecting a Charge Point in ChangeConfiguration makes the conf. key list empty.

### CODE REVIEW

**Comment by goekay** [comment]
help me if i understand it correctly: if you press perform without selecting a charge point, you get a validation error page. you want to preserve the selected configuration key on that page to make it easier to continue?

**Comment by JavaIsJavaScript** [comment]
All the configuration keys dissapear when you don't select a Charge Point and press perform

**Comment by goekay** [comment]
hmm. this problem exists in older ocpp version controllers, too. so i would look for a general solution.

**Comment by JavaIsJavaScript** [comment]
not sure if this happens in older ocpp version, will test it now, maybe it's because in ocpp1.6 conf. keys can be ReadOnly or ReadWrite

**Comment by goekay** [comment]
it for sure exists in ocpp 1.2. just tested it. the line `model.addAttribute("ocppConfKeys", getConfigurationKeys());` is missing in postChangeConf there, too.

**Comment by JavaIsJavaScript** [comment]
maybe handle this problem like GetConfiguration is handled and add "postChangeConf" to all the controllers since all ocpp versions need a different list of configuration keys?

**Comment by goekay** [comment]
i have implemented a solution that modifies getConfigurationKeys. please tell me if you approve it. i am committing it in a few minutes.

**Comment by JavaIsJavaScript** [comment]
works like a charm :)

**Comment by goekay** [comment]
great. thanks for your help and involvement!

**Pull request closed without merging**
